CREATE USER IF NOT EXISTS jon.doe IDENTIFIED WITH mysql_native_password BY 'change_me';
CREATE USER IF NOT EXISTS john IDENTIFIED WITH mysql_native_password BY pw1;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON JenkinsPlayground.* TO jon.doe;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON JenkinsPlayground.* TO john;

